---
.gitignore:
  paths:
    - '.vagrant'
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
Gemfile:
  optional:
    ':development':
      - gem: 'bolt'
spec/spec_helper.rb:
  mock_with: ':rspec'
